-- MySQL Script generated by MySQL Workbench
-- Sat Nov 15 16:41:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokeamigos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pokeamigos` ;

-- -----------------------------------------------------
-- Schema pokeamigos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokeamigos` DEFAULT CHARACTER SET utf8 ;
USE `pokeamigos` ;

-- -----------------------------------------------------
-- Table `pokeamigos`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Usuario` (
  `UsuId` INT NOT NULL AUTO_INCREMENT,
  `UsuMail` VARCHAR(45) NOT NULL,
  `UsuHash` VARCHAR(45) NOT NULL,
  `UsuNm` VARCHAR(45) NOT NULL,
  `Usuariocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UsuId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Album` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Album` (
  `AlbId` INT NOT NULL,
  `IsWish` TINYINT NOT NULL,
  `IdUsu` INT NOT NULL,
  PRIMARY KEY (`AlbId`),
  INDEX `IdUsu_idx` (`IdUsu` ASC) VISIBLE,
  CONSTRAINT `IdUsu`
    FOREIGN KEY (`IdUsu`)
    REFERENCES `pokeamigos`.`Usuario` (`UsuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Tipo_Carta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Tipo_Carta` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Tipo_Carta` (
  `TpCId` INT NOT NULL AUTO_INCREMENT,
  `TpCNm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TpCId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Colecao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Colecao` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Colecao` (
  `CltId` INT NOT NULL AUTO_INCREMENT,
  `CltNm` VARCHAR(45) NOT NULL,
  `CltSg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CltId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Artista` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Artista` (
  `ArtId` INT NOT NULL AUTO_INCREMENT,
  `ArtNm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ArtId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Elemento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Elemento` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Elemento` (
  `ElmId` INT NOT NULL AUTO_INCREMENT,
  `ElmNm` VARCHAR(45) NOT NULL,
  `ElmImg` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`ElmId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Carta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Carta` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Carta` (
  `CrdId` INT NOT NULL AUTO_INCREMENT,
  `TpCId` INT NOT NULL,
  `CltId` INT NOT NULL,
  `ArtId` INT,
  `CrdPtvs` INT,
  `CrdImg` VARCHAR(300) NOT NULL,
  `ElmId` INT,
  `CrdNm` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CrdId`),
  INDEX `IdTpC_Carta_idx` (`TpCId` ASC) VISIBLE,
  INDEX `CltId_Carta_idx` (`CltId` ASC) VISIBLE,
  INDEX `ArtId_Carta_idx` (`ArtId` ASC) VISIBLE,
  INDEX `ElmId_Carta_idx` (`ElmId` ASC) VISIBLE,
  CONSTRAINT `TpCId_Carta`
    FOREIGN KEY (`TpCId`)
    REFERENCES `pokeamigos`.`Tipo_Carta` (`TpCId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CltId_Carta`
    FOREIGN KEY (`CltId`)
    REFERENCES `pokeamigos`.`Colecao` (`CltId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ArtId_Carta`
    FOREIGN KEY (`ArtId`)
    REFERENCES `pokeamigos`.`Artista` (`ArtId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ElmId_Carta`
    FOREIGN KEY (`ElmId`)
    REFERENCES `pokeamigos`.`Elemento` (`ElmId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Album_Carta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Album_Carta` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Album_Carta` (
  `Album_CartaId` INT NOT NULL,
  `AlbId` INT NOT NULL,
  `CrdId` INT NOT NULL,
  PRIMARY KEY (`Album_CartaId`),
  INDEX `AlbId_idx` (`AlbId` ASC) VISIBLE,
  INDEX `CrdId__Carta_Album_idx` (`CrdId` ASC) VISIBLE,
  CONSTRAINT `AlbId_Carta_Album`
    FOREIGN KEY (`AlbId`)
    REFERENCES `pokeamigos`.`Album` (`AlbId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CrdId__Carta_Album`
    FOREIGN KEY (`CrdId`)
    REFERENCES `pokeamigos`.`Carta` (`CrdId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Loja` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Loja` (
  `LojId` INT NOT NULL AUTO_INCREMENT,
  `LojNm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LojId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Tipo_Foil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Tipo_Foil` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Tipo_Foil` (
  `TpFId` INT NOT NULL AUTO_INCREMENT,
  `TpFNm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TpFId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokeamigos`.`Anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokeamigos`.`Anuncio` ;

CREATE TABLE IF NOT EXISTS `pokeamigos`.`Anuncio` (
  `AnuId` INT NOT NULL AUTO_INCREMENT,
  `LojId` INT NOT NULL,
  `CrdId` INT NOT NULL,
  `AnuVlr` FLOAT NOT NULL,
  `TpFId` INT NOT NULL,
  PRIMARY KEY (`AnuId`),
  INDEX `LojId_Anuncio_idx` (`LojId` ASC) VISIBLE,
  INDEX `CrdId_Anuncio_idx` (`CrdId` ASC) VISIBLE,
  INDEX `TpFId_Anuncio_idx` (`TpFId` ASC) VISIBLE,
  CONSTRAINT `LojId_Anuncio`
    FOREIGN KEY (`LojId`)
    REFERENCES `pokeamigos`.`Loja` (`LojId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CrdId_Anuncio`
    FOREIGN KEY (`CrdId`)
    REFERENCES `pokeamigos`.`Carta` (`CrdId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TpFId_Anuncio`
    FOREIGN KEY (`TpFId`)
    REFERENCES `pokeamigos`.`Tipo_Foil` (`TpFId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO Colecao (CltNm, CltSg) 
  values ("151", "MEW"),
        ("Megaevolução", "MEG"),
        ("Evoluções Prismáticas", "PRE"),
        ("Amigos da Jornada", "JTG"),
        ("Raio Preto", "BLK"),
        ("Fogo Branco", "WHT");

INSERT INTO Elemento (ElmImg, ElmNm) 
  values ("https://static.tcgcollector.com/content/images/c5/ec/16/c5ec1646156fdb6d2db562afa7ec0e9b250cc023b7d5955d93265ebb23808031.png", "Grama"),
    ("https://static.tcgcollector.com/content/images/98/fa/64/98fa649102fdbf170a2be997d5ecf2016b2f5f92f372213e9e642f7ed9332993.png", "Normal"),
    ("https://static.tcgcollector.com/content/images/2f/ba/6d/2fba6dc107035a268ab62384c736f7a96cdffd1080d0b2126917e074487c958b.png", "Escuridão"),
    ("https://static.tcgcollector.com/content/images/e7/49/a5/e749a52e91db7e684aa3d595e89badee67a5ebdaf77177977e70a71f76d447db.png", "Luta"),
    ("https://static.tcgcollector.com/content/images/1b/e4/e8/1be4e8211f0be0a51b792b6c31f34814f03d933feefda27d04b7516b611f3faf.png", "Raio"),
    ("https://static.tcgcollector.com/content/images/66/ae/d9/66aed9c41d50cf8cee23597eb761a6767cabc73f6c610d54f599c3d2624da37c.png", "Metal"),
    ("https://static.tcgcollector.com/content/images/73/9f/ff/739fff897f789c085e47b79c223a66045a2bacf6340ae3ab347a7153c2406032.png", "Dragão"),
    ("https://static.tcgcollector.com/content/images/bf/88/e3/bf88e3320870f157113cd48e0965ac9a0fa1630746041f59f07db92a9debf2ad.png", "Psíquica"),
    ("https://static.tcgcollector.com/content/images/44/ab/dd/44abdd03385169a860610e23914434a0b94ccdaa86fae497d7726f99370c3386.png", "Fogo"),
    ("https://static.tcgcollector.com/content/images/a6/d1/d1/a6d1d1d31a4470f019db8ea0132c41054cd8c35e295eb3b33d7c849225b7073e.png", "Água"),
    ("https://static.tcgcollector.com/content/images/b4/4a/ee/b44aeec9123f7cd83e0bf93d72be2dc2cacd1671de571d87d2ccf665124aa829.png", "Fada");